language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_install:
  - rm composer.lock

install:
  - composer install

before_script:
  - mysql -e 'CREATE DATABASE cept_ex;'
  - mysql -u root < data/cept_ex.sql

script:
  - vendor/bin/codecept run